// <auto-generated />
using System;
using Appointment_SaaS.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Appointment_SaaS.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260211184918_UpdateProperty")]
    partial class UpdateProperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.AppUser", b =>
                {
                    b.Property<int>("AppUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppUserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenantID")
                        .HasColumnType("int");

                    b.HasKey("AppUserID");

                    b.HasIndex("TenantID");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.Appointment", b =>
                {
                    b.Property<int>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentID"));

                    b.Property<int>("AppUserID")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenantID")
                        .HasColumnType("int");

                    b.HasKey("AppointmentID");

                    b.HasIndex("AppUserID");

                    b.HasIndex("ServiceID");

                    b.HasIndex("TenantID");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.Sector", b =>
                {
                    b.Property<int>("SectorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectorID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultPrompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SectorID");

                    b.ToTable("Sectors");

                    b.HasData(
                        new
                        {
                            SectorID = 1,
                            CreatedAt = new DateTime(2026, 2, 11, 21, 49, 16, 503, DateTimeKind.Local).AddTicks(539),
                            DefaultPrompt = "Sen profesyonel bir erkek kuaförü asistanısın. Maskülen, net ve çözüm odaklı konuş.",
                            Name = "Erkek Kuaförü"
                        },
                        new
                        {
                            SectorID = 2,
                            CreatedAt = new DateTime(2026, 2, 11, 21, 49, 16, 503, DateTimeKind.Local).AddTicks(560),
                            DefaultPrompt = "Sen nazik ve detaycı bir kadın kuaförü asistanısın. Estetik ve bakım konularına hakim konuş.",
                            Name = "Kadın Kuaförü"
                        },
                        new
                        {
                            SectorID = 3,
                            CreatedAt = new DateTime(2026, 2, 11, 21, 49, 16, 503, DateTimeKind.Local).AddTicks(563),
                            DefaultPrompt = "Sen modern ve kapsayıcı bir kuaför asistanısın. Her türlü bakım hizmetine uygun profesyonel bir dille konuş.",
                            Name = "Unisex Kuaför"
                        });
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.Service", b =>
                {
                    b.Property<int>("ServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceID"));

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TenantID")
                        .HasColumnType("int");

                    b.HasKey("ServiceID");

                    b.HasIndex("TenantID");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceID = 1,
                            DurationInMinutes = 30,
                            Name = "Saç Kesimi",
                            Price = 250m,
                            TenantID = 1
                        },
                        new
                        {
                            ServiceID = 2,
                            DurationInMinutes = 20,
                            Name = "Sakal Tıraşı",
                            Price = 150m,
                            TenantID = 1
                        },
                        new
                        {
                            ServiceID = 3,
                            DurationInMinutes = 45,
                            Name = "Cilt Bakımı",
                            Price = 400m,
                            TenantID = 1
                        },
                        new
                        {
                            ServiceID = 4,
                            DurationInMinutes = 30,
                            Name = "Fön",
                            Price = 200m,
                            TenantID = 2
                        },
                        new
                        {
                            ServiceID = 5,
                            DurationInMinutes = 120,
                            Name = "Boya",
                            Price = 1200m,
                            TenantID = 2
                        },
                        new
                        {
                            ServiceID = 6,
                            DurationInMinutes = 40,
                            Name = "Manikür",
                            Price = 350m,
                            TenantID = 2
                        },
                        new
                        {
                            ServiceID = 7,
                            DurationInMinutes = 60,
                            Name = "Modern Kesim",
                            Price = 500m,
                            TenantID = 3
                        },
                        new
                        {
                            ServiceID = 8,
                            DurationInMinutes = 90,
                            Name = "Keratin Bakım",
                            Price = 1500m,
                            TenantID = 3
                        },
                        new
                        {
                            ServiceID = 9,
                            DurationInMinutes = 30,
                            Name = "Kaş Dizayn",
                            Price = 300m,
                            TenantID = 3
                        });
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.Tenant", b =>
                {
                    b.Property<int>("TenantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBotActive")
                        .HasColumnType("bit");

                    b.Property<int>("MessageCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SectorID")
                        .HasColumnType("int");

                    b.Property<string>("WabaID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenantID");

                    b.HasIndex("SectorID");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            TenantID = 1,
                            Address = "İstanbul, Şişli No:10",
                            ApiKey = "JNT-123-ABC",
                            CreatedAt = new DateTime(2026, 2, 11, 21, 49, 16, 503, DateTimeKind.Local).AddTicks(1115),
                            IsActive = true,
                            IsBotActive = true,
                            MessageCount = 0,
                            Name = "Janti Erkek Kuaförü",
                            PhoneNumber = "5551112233",
                            SectorID = 1,
                            WabaID = "W101"
                        },
                        new
                        {
                            TenantID = 2,
                            Address = "Ankara, Çankaya No:25",
                            ApiKey = "ISL-456-DEF",
                            CreatedAt = new DateTime(2026, 2, 11, 21, 49, 16, 503, DateTimeKind.Local).AddTicks(1121),
                            IsActive = true,
                            IsBotActive = true,
                            MessageCount = 0,
                            Name = "Işıltı Bayan Salonu",
                            PhoneNumber = "5552223344",
                            SectorID = 2,
                            WabaID = "W202"
                        },
                        new
                        {
                            TenantID = 3,
                            Address = "İzmir, Alsancak No:5",
                            ApiKey = "MOD-789-GHI",
                            CreatedAt = new DateTime(2026, 2, 11, 21, 49, 16, 503, DateTimeKind.Local).AddTicks(1125),
                            IsActive = true,
                            IsBotActive = true,
                            MessageCount = 0,
                            Name = "Modern Tarz Unisex",
                            PhoneNumber = "5553334455",
                            SectorID = 3,
                            WabaID = "W303"
                        });
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.AppUser", b =>
                {
                    b.HasOne("Appointment_SaaS.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.Appointment", b =>
                {
                    b.HasOne("Appointment_SaaS.Core.Entities.AppUser", "AppUser")
                        .WithMany("Appointments")
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Appointment_SaaS.Core.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Appointment_SaaS.Core.Entities.Tenant", "Tenant")
                        .WithMany("Appointments")
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Service");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.Service", b =>
                {
                    b.HasOne("Appointment_SaaS.Core.Entities.Tenant", "Tenant")
                        .WithMany("Services")
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.Tenant", b =>
                {
                    b.HasOne("Appointment_SaaS.Core.Entities.Sector", "Sector")
                        .WithMany("Tenants")
                        .HasForeignKey("SectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.AppUser", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.Sector", b =>
                {
                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.Tenant", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
