// <auto-generated />
using Appointment_SaaS.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Appointment_SaaS.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521120000_AddScheduledPlanChangeFields")]
    partial class AddScheduledPlanChangeFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Runtime'da Up() kullanılır; model anlık görüntüsü AppDbContextModelSnapshot'ta.
#pragma warning restore 612, 618
        }
    }
}
