// <auto-generated />
using System;
using Appointment_SaaS.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Appointment_SaaS.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.AppUser", b =>
                {
                    b.Property<int>("AppUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppUserID"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleCalendarId")
                        .HasColumnType("text");

                    b.Property<string>("GoogleRefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastOtpRequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OtpCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Specialization")
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<int>("TenantID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TrialEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TrialStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AppUserID");

                    b.HasIndex("TenantID");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            AppUserID = -1,
                            AccessFailedCount = 0,
                            Email = "admin@appointmentsaas.com",
                            FirstName = "Kurucu",
                            LastName = "Admin",
                            PhoneNumber = "05078283441",
                            SecurityStamp = "e75bba40-b367-47f2-a7fe-91a8e552f47d",
                            Status = true,
                            TenantID = 1
                        });
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.Appointment", b =>
                {
                    b.Property<int>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppointmentID"));

                    b.Property<int>("AppUserID")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoogleEventID")
                        .HasColumnType("text");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReminderSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ServiceID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantID")
                        .HasColumnType("integer");

                    b.HasKey("AppointmentID");

                    b.HasIndex("AppUserID");

                    b.HasIndex("ServiceID");

                    b.HasIndex("TenantID", "AppUserID", "StartDate", "EndDate")
                        .IsUnique()
                        .HasDatabaseName("IX_Appointment_Tenant_Staff_Slot");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.AppointmentServiceLink", b =>
                {
                    b.Property<int>("AppointmentServiceLinkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppointmentServiceLinkID"));

                    b.Property<int>("AppointmentID")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceID")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("AppointmentServiceLinkID");

                    b.HasIndex("AppointmentID");

                    b.HasIndex("ServiceID");

                    b.ToTable("AppointmentServiceLinks");
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.AuditLog", b =>
                {
                    b.Property<int>("AuditLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuditLogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("AuditLogID");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.BusinessHour", b =>
                {
                    b.Property<int>("BusinessHourID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BusinessHourID"));

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("interval");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("interval");

                    b.Property<int>("TenantID")
                        .HasColumnType("integer");

                    b.HasKey("BusinessHourID");

                    b.HasIndex("TenantID");

                    b.ToTable("BusinessHours");

                    b.HasData(
                        new
                        {
                            BusinessHourID = 1,
                            CloseTime = new TimeSpan(0, 20, 0, 0, 0),
                            DayOfWeek = 1,
                            IsClosed = false,
                            OpenTime = new TimeSpan(0, 9, 0, 0, 0),
                            TenantID = 1
                        },
                        new
                        {
                            BusinessHourID = 2,
                            CloseTime = new TimeSpan(0, 20, 0, 0, 0),
                            DayOfWeek = 2,
                            IsClosed = false,
                            OpenTime = new TimeSpan(0, 9, 0, 0, 0),
                            TenantID = 1
                        },
                        new
                        {
                            BusinessHourID = 3,
                            CloseTime = new TimeSpan(0, 20, 0, 0, 0),
                            DayOfWeek = 3,
                            IsClosed = false,
                            OpenTime = new TimeSpan(0, 9, 0, 0, 0),
                            TenantID = 1
                        },
                        new
                        {
                            BusinessHourID = 4,
                            CloseTime = new TimeSpan(0, 20, 0, 0, 0),
                            DayOfWeek = 4,
                            IsClosed = false,
                            OpenTime = new TimeSpan(0, 9, 0, 0, 0),
                            TenantID = 1
                        },
                        new
                        {
                            BusinessHourID = 5,
                            CloseTime = new TimeSpan(0, 20, 0, 0, 0),
                            DayOfWeek = 5,
                            IsClosed = false,
                            OpenTime = new TimeSpan(0, 9, 0, 0, 0),
                            TenantID = 1
                        },
                        new
                        {
                            BusinessHourID = 6,
                            CloseTime = new TimeSpan(0, 20, 0, 0, 0),
                            DayOfWeek = 6,
                            IsClosed = false,
                            OpenTime = new TimeSpan(0, 9, 0, 0, 0),
                            TenantID = 1
                        },
                        new
                        {
                            BusinessHourID = 7,
                            CloseTime = new TimeSpan(0, 0, 0, 0, 0),
                            DayOfWeek = 0,
                            IsClosed = true,
                            OpenTime = new TimeSpan(0, 0, 0, 0, 0),
                            TenantID = 1
                        });
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.Feedback", b =>
                {
                    b.Property<int>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FeedbackID"));

                    b.Property<string>("FeedbackType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TenantID")
                        .HasColumnType("integer");

                    b.HasKey("FeedbackID");

                    b.HasIndex("TenantID");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Holidays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2026, 1, 1),
                            IsDefault = true,
                            Name = "Yılbaşı",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2026, 3, 20),
                            IsDefault = true,
                            Name = "Ramazan Bayramı 1. Gün",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2026, 3, 21),
                            IsDefault = true,
                            Name = "Ramazan Bayramı 2. Gün",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2026, 3, 22),
                            IsDefault = true,
                            Name = "Ramazan Bayramı 3. Gün",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2026, 4, 23),
                            IsDefault = true,
                            Name = "Ulusal Egemenlik ve Çocuk Bayramı",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateOnly(2026, 5, 1),
                            IsDefault = true,
                            Name = "Emek ve Dayanışma Günü",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateOnly(2026, 5, 19),
                            IsDefault = true,
                            Name = "Atatürk'ü Anma, Gençlik ve Spor Bayramı",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateOnly(2026, 5, 26),
                            IsDefault = true,
                            Name = "Kurban Bayramı Arifesi",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateOnly(2026, 5, 27),
                            IsDefault = true,
                            Name = "Kurban Bayramı 1. Gün",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateOnly(2026, 5, 28),
                            IsDefault = true,
                            Name = "Kurban Bayramı 2. Gün",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateOnly(2026, 5, 29),
                            IsDefault = true,
                            Name = "Kurban Bayramı 3. Gün",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateOnly(2026, 5, 30),
                            IsDefault = true,
                            Name = "Kurban Bayramı 4. Gün",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateOnly(2026, 7, 15),
                            IsDefault = true,
                            Name = "Demokrasi ve Millî Birlik Günü",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateOnly(2026, 8, 30),
                            IsDefault = true,
                            Name = "Zafer Bayramı",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateOnly(2026, 10, 29),
                            IsDefault = true,
                            Name = "Cumhuriyet Bayramı",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateOnly(2026, 11, 10),
                            IsDefault = true,
                            Name = "Atatürkü Anma Günü",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateOnly(2026, 1, 1),
                            IsDefault = true,
                            Name = "Yılbaşı",
                            TenantId = 2
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateOnly(2026, 3, 20),
                            IsDefault = true,
                            Name = "Ramazan Bayramı 1. Gün",
                            TenantId = 2
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateOnly(2026, 3, 21),
                            IsDefault = true,
                            Name = "Ramazan Bayramı 2. Gün",
                            TenantId = 2
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateOnly(2026, 3, 22),
                            IsDefault = true,
                            Name = "Ramazan Bayramı 3. Gün",
                            TenantId = 2
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateOnly(2026, 4, 23),
                            IsDefault = true,
                            Name = "Ulusal Egemenlik ve Çocuk Bayramı",
                            TenantId = 2
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateOnly(2026, 5, 1),
                            IsDefault = true,
                            Name = "Emek ve Dayanışma Günü",
                            TenantId = 2
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateOnly(2026, 5, 19),
                            IsDefault = true,
                            Name = "Atatürk'ü Anma, Gençlik ve Spor Bayramı",
                            TenantId = 2
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateOnly(2026, 5, 26),
                            IsDefault = true,
                            Name = "Kurban Bayramı Arifesi",
                            TenantId = 2
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateOnly(2026, 5, 27),
                            IsDefault = true,
                            Name = "Kurban Bayramı 1. Gün",
                            TenantId = 2
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateOnly(2026, 5, 28),
                            IsDefault = true,
                            Name = "Kurban Bayramı 2. Gün",
                            TenantId = 2
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateOnly(2026, 5, 29),
                            IsDefault = true,
                            Name = "Kurban Bayramı 3. Gün",
                            TenantId = 2
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateOnly(2026, 5, 30),
                            IsDefault = true,
                            Name = "Kurban Bayramı 4. Gün",
                            TenantId = 2
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateOnly(2026, 7, 15),
                            IsDefault = true,
                            Name = "Demokrasi ve Millî Birlik Günü",
                            TenantId = 2
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateOnly(2026, 8, 30),
                            IsDefault = true,
                            Name = "Zafer Bayramı",
                            TenantId = 2
                        },
                        new
                        {
                            Id = 31,
                            Date = new DateOnly(2026, 10, 29),
                            IsDefault = true,
                            Name = "Cumhuriyet Bayramı",
                            TenantId = 2
                        },
                        new
                        {
                            Id = 32,
                            Date = new DateOnly(2026, 11, 10),
                            IsDefault = true,
                            Name = "Atatürkü Anma Günü",
                            TenantId = 2
                        },
                        new
                        {
                            Id = 33,
                            Date = new DateOnly(2026, 1, 1),
                            IsDefault = true,
                            Name = "Yılbaşı",
                            TenantId = 3
                        },
                        new
                        {
                            Id = 34,
                            Date = new DateOnly(2026, 3, 20),
                            IsDefault = true,
                            Name = "Ramazan Bayramı 1. Gün",
                            TenantId = 3
                        },
                        new
                        {
                            Id = 35,
                            Date = new DateOnly(2026, 3, 21),
                            IsDefault = true,
                            Name = "Ramazan Bayramı 2. Gün",
                            TenantId = 3
                        },
                        new
                        {
                            Id = 36,
                            Date = new DateOnly(2026, 3, 22),
                            IsDefault = true,
                            Name = "Ramazan Bayramı 3. Gün",
                            TenantId = 3
                        },
                        new
                        {
                            Id = 37,
                            Date = new DateOnly(2026, 4, 23),
                            IsDefault = true,
                            Name = "Ulusal Egemenlik ve Çocuk Bayramı",
                            TenantId = 3
                        },
                        new
                        {
                            Id = 38,
                            Date = new DateOnly(2026, 5, 1),
                            IsDefault = true,
                            Name = "Emek ve Dayanışma Günü",
                            TenantId = 3
                        },
                        new
                        {
                            Id = 39,
                            Date = new DateOnly(2026, 5, 19),
                            IsDefault = true,
                            Name = "Atatürk'ü Anma, Gençlik ve Spor Bayramı",
                            TenantId = 3
                        },
                        new
                        {
                            Id = 40,
                            Date = new DateOnly(2026, 5, 26),
                            IsDefault = true,
                            Name = "Kurban Bayramı Arifesi",
                            TenantId = 3
                        },
                        new
                        {
                            Id = 41,
                            Date = new DateOnly(2026, 5, 27),
                            IsDefault = true,
                            Name = "Kurban Bayramı 1. Gün",
                            TenantId = 3
                        },
                        new
                        {
                            Id = 42,
                            Date = new DateOnly(2026, 5, 28),
                            IsDefault = true,
                            Name = "Kurban Bayramı 2. Gün",
                            TenantId = 3
                        },
                        new
                        {
                            Id = 43,
                            Date = new DateOnly(2026, 5, 29),
                            IsDefault = true,
                            Name = "Kurban Bayramı 3. Gün",
                            TenantId = 3
                        },
                        new
                        {
                            Id = 44,
                            Date = new DateOnly(2026, 5, 30),
                            IsDefault = true,
                            Name = "Kurban Bayramı 4. Gün",
                            TenantId = 3
                        },
                        new
                        {
                            Id = 45,
                            Date = new DateOnly(2026, 7, 15),
                            IsDefault = true,
                            Name = "Demokrasi ve Millî Birlik Günü",
                            TenantId = 3
                        },
                        new
                        {
                            Id = 46,
                            Date = new DateOnly(2026, 8, 30),
                            IsDefault = true,
                            Name = "Zafer Bayramı",
                            TenantId = 3
                        },
                        new
                        {
                            Id = 47,
                            Date = new DateOnly(2026, 10, 29),
                            IsDefault = true,
                            Name = "Cumhuriyet Bayramı",
                            TenantId = 3
                        },
                        new
                        {
                            Id = 48,
                            Date = new DateOnly(2026, 11, 10),
                            IsDefault = true,
                            Name = "Atatürkü Anma Günü",
                            TenantId = 3
                        });
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.OperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OperationClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Staff"
                        });
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.Sector", b =>
                {
                    b.Property<int>("SectorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SectorID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultPrompt")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SectorID");

                    b.ToTable("Sectors");

                    b.HasData(
                        new
                        {
                            SectorID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultPrompt = "Sen profesyonel bir erkek kuaförü asistanısın. Maskülen, net ve çözüm odaklı konuş.",
                            Name = "Erkek Kuaförü"
                        },
                        new
                        {
                            SectorID = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultPrompt = "Sen nazik ve detaycı bir kadın kuaförü asistanısın. Estetik ve bakım konularına hakim konuş.",
                            Name = "Kadın Kuaförü"
                        },
                        new
                        {
                            SectorID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultPrompt = "Sen modern ve kapsayıcı bir kuaför asistanısın. Her türlü bakım hizmetine uygun profesyonel bir dille konuş.",
                            Name = "Unisex Kuaför"
                        });
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.Service", b =>
                {
                    b.Property<int>("ServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServiceID"));

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TenantID")
                        .HasColumnType("integer");

                    b.HasKey("ServiceID");

                    b.HasIndex("TenantID");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceID = 1,
                            DurationInMinutes = 30,
                            Name = "Saç Kesimi",
                            Price = 250m,
                            TenantID = 1
                        },
                        new
                        {
                            ServiceID = 2,
                            DurationInMinutes = 20,
                            Name = "Sakal Tıraşı",
                            Price = 150m,
                            TenantID = 1
                        },
                        new
                        {
                            ServiceID = 3,
                            DurationInMinutes = 45,
                            Name = "Cilt Bakımı",
                            Price = 400m,
                            TenantID = 1
                        },
                        new
                        {
                            ServiceID = 4,
                            DurationInMinutes = 30,
                            Name = "Fön",
                            Price = 200m,
                            TenantID = 2
                        },
                        new
                        {
                            ServiceID = 5,
                            DurationInMinutes = 120,
                            Name = "Boya",
                            Price = 1200m,
                            TenantID = 2
                        },
                        new
                        {
                            ServiceID = 6,
                            DurationInMinutes = 40,
                            Name = "Manikür",
                            Price = 350m,
                            TenantID = 2
                        },
                        new
                        {
                            ServiceID = 7,
                            DurationInMinutes = 60,
                            Name = "Modern Kesim",
                            Price = 500m,
                            TenantID = 3
                        },
                        new
                        {
                            ServiceID = 8,
                            DurationInMinutes = 90,
                            Name = "Keratin Bakım",
                            Price = 1500m,
                            TenantID = 3
                        },
                        new
                        {
                            ServiceID = 9,
                            DurationInMinutes = 30,
                            Name = "Kaş Dizayn",
                            Price = 300m,
                            TenantID = 3
                        });
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.Tenant", b =>
                {
                    b.Property<int>("TenantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TenantID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("boolean");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("BreakEndTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("interval")
                        .HasDefaultValue(new TimeSpan(0, 13, 0, 0, 0));

                    b.Property<TimeSpan>("BreakStartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("interval")
                        .HasDefaultValue(new TimeSpan(0, 12, 0, 0, 0));

                    b.Property<bool>("BreakTimeEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoogleAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("GoogleEmail")
                        .HasColumnType("text");

                    b.Property<string>("InstanceName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBlacklisted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsBotActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSubscriptionActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrial")
                        .HasColumnType("boolean");

                    b.Property<string>("IyzicoCardToken")
                        .HasColumnType("text");

                    b.Property<string>("IyzicoUserKey")
                        .HasColumnType("text");

                    b.Property<int>("MessageCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PendingBillingCycle")
                        .HasColumnType("text");

                    b.Property<string>("PendingCheckoutToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PendingPlanEffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PendingPlanType")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviousSubscriptionReferenceCode")
                        .HasColumnType("text");

                    b.Property<int>("SectorID")
                        .HasColumnType("integer");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("text");

                    b.Property<DateTime>("SubscriptionEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubscriptionReferenceCode")
                        .HasColumnType("text");

                    b.Property<string>("TrialFingerprint")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<bool>("TrialUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("TenantID");

                    b.HasIndex("SectorID");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            TenantID = 1,
                            Address = "İstanbul, Şişli No:10",
                            ApiKey = "JNT-123-ABC",
                            AutoRenew = true,
                            BillingCycle = "Monthly",
                            BreakEndTime = new TimeSpan(0, 13, 0, 0, 0),
                            BreakStartTime = new TimeSpan(0, 12, 0, 0, 0),
                            BreakTimeEnabled = true,
                            CancelAtPeriodEnd = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsBlacklisted = false,
                            IsBotActive = true,
                            IsSubscriptionActive = true,
                            IsTrial = false,
                            MessageCount = 0,
                            Name = "Janti Erkek Kuaförü",
                            PhoneNumber = "5551112233",
                            PlanType = "Trial",
                            SectorID = 1,
                            SubscriptionEndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            TrialFingerprint = "",
                            TrialUsed = false
                        },
                        new
                        {
                            TenantID = 2,
                            Address = "Ankara, Çankaya No:25",
                            ApiKey = "ISL-456-DEF",
                            AutoRenew = true,
                            BillingCycle = "Monthly",
                            BreakEndTime = new TimeSpan(0, 13, 0, 0, 0),
                            BreakStartTime = new TimeSpan(0, 12, 0, 0, 0),
                            BreakTimeEnabled = true,
                            CancelAtPeriodEnd = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsBlacklisted = false,
                            IsBotActive = true,
                            IsSubscriptionActive = true,
                            IsTrial = false,
                            MessageCount = 0,
                            Name = "Işıltı Bayan Salonu",
                            PhoneNumber = "5552223344",
                            PlanType = "Trial",
                            SectorID = 2,
                            SubscriptionEndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            TrialFingerprint = "",
                            TrialUsed = false
                        },
                        new
                        {
                            TenantID = 3,
                            Address = "İzmir, Alsancak No:5",
                            ApiKey = "MOD-789-GHI",
                            AutoRenew = true,
                            BillingCycle = "Monthly",
                            BreakEndTime = new TimeSpan(0, 13, 0, 0, 0),
                            BreakStartTime = new TimeSpan(0, 12, 0, 0, 0),
                            BreakTimeEnabled = true,
                            CancelAtPeriodEnd = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsBlacklisted = false,
                            IsBotActive = true,
                            IsSubscriptionActive = true,
                            IsTrial = false,
                            MessageCount = 0,
                            Name = "Modern Tarz Unisex",
                            PhoneNumber = "5553334455",
                            PlanType = "Trial",
                            SectorID = 3,
                            SubscriptionEndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            TrialFingerprint = "",
                            TrialUsed = false
                        });
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.TenantBlockedPhone", b =>
                {
                    b.Property<int>("TenantBlockedPhoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TenantBlockedPhoneID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("PhoneCore")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TenantID")
                        .HasColumnType("integer");

                    b.HasKey("TenantBlockedPhoneID");

                    b.HasIndex("TenantID", "PhoneCore")
                        .IsUnique();

                    b.ToTable("TenantBlockedPhones");
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.TransactionLog", b =>
                {
                    b.Property<int>("TransactionLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionLogID"));

                    b.Property<string>("AgreementVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PaymentId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RawPayload")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SubscriptionReferenceCode")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("TransactionLogID");

                    b.HasIndex("PaymentId")
                        .IsUnique()
                        .HasFilter("[PaymentId] IS NOT NULL");

                    b.ToTable("TransactionLogs");
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.UserOperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OperationClaimId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserOperationClaims");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            OperationClaimId = 1,
                            UserId = -1
                        });
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.AppUser", b =>
                {
                    b.HasOne("Appointment_SaaS.Core.Entities.Tenant", "Tenant")
                        .WithMany("AppUsers")
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.Appointment", b =>
                {
                    b.HasOne("Appointment_SaaS.Core.Entities.AppUser", "AppUser")
                        .WithMany("Appointments")
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Appointment_SaaS.Core.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Appointment_SaaS.Core.Entities.Tenant", "Tenant")
                        .WithMany("Appointments")
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Service");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.AppointmentServiceLink", b =>
                {
                    b.HasOne("Appointment_SaaS.Core.Entities.Appointment", "Appointment")
                        .WithMany("AppointmentServiceLinks")
                        .HasForeignKey("AppointmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Appointment_SaaS.Core.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.BusinessHour", b =>
                {
                    b.HasOne("Appointment_SaaS.Core.Entities.Tenant", "Tenant")
                        .WithMany("BusinessHours")
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.Feedback", b =>
                {
                    b.HasOne("Appointment_SaaS.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.Holiday", b =>
                {
                    b.HasOne("Appointment_SaaS.Core.Entities.Tenant", "Tenant")
                        .WithMany("Holidays")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.Service", b =>
                {
                    b.HasOne("Appointment_SaaS.Core.Entities.Tenant", "Tenant")
                        .WithMany("Services")
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.Tenant", b =>
                {
                    b.HasOne("Appointment_SaaS.Core.Entities.Sector", "Sector")
                        .WithMany("Tenants")
                        .HasForeignKey("SectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.TenantBlockedPhone", b =>
                {
                    b.HasOne("Appointment_SaaS.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.AppUser", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.Appointment", b =>
                {
                    b.Navigation("AppointmentServiceLinks");
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.Sector", b =>
                {
                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("Appointment_SaaS.Core.Entities.Tenant", b =>
                {
                    b.Navigation("AppUsers");

                    b.Navigation("Appointments");

                    b.Navigation("BusinessHours");

                    b.Navigation("Holidays");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
